version: 1
applications:
  - appRoot: .
    frontend:
      phases:
        preBuild:
          commands:
            # Node.js バージョン確認
            - node --version
            - npm --version
            # Amplify Backend から amplify_outputs.json を取得
            - echo "Copying amplify_outputs.json to frontend..."
            - cp amplify_outputs.json frontend/amplify_outputs.json || echo "amplify_outputs.json not found in root, checking other locations..."
            # Frontend 依存関係インストール
            - cd frontend
            - npm ci --legacy-peer-deps
        build:
          commands:
            # amplify_outputs.json の存在確認
            - ls -la amplify_outputs.json || echo "Warning: amplify_outputs.json not found"
            # Next.js 静的エクスポートビルド
            - npm run build
            # ビルド結果確認
            - ls -la out/ || echo "Warning: out directory not found"
      artifacts:
        # 静的エクスポート用（output: 'export'）
        baseDirectory: frontend/out
        files:
          - '**/*'
      cache:
        paths:
          - frontend/node_modules/**/*
    backend:
      phases:
        preBuild:
          commands:
            # Amplify Backend 依存関係インストール
            - cd amplify
            - npm ci
        build:
          commands:
            # Amplify Backend デプロイ
            - npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
      buildSizeConfig:
        maxSize: 500MB
    environmentVariables:
      # Bedrock リージョン（東京リージョン）
      BEDROCK_REGION: ap-northeast-1
      # ログレベル
      LOG_LEVEL: INFO
